version: '3.3'

services:
  front:
    build: ./Front
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - backend
      - db
    volumes:
      - ./Front/src:/usr/share/nginx/html

  backend:
    build: ./Backend
    container_name: flask
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./Backend:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.13
    container_name: mysql
    restart: always
    ports:
      - 3306:3306 

    env_file:
      - common.env
    
    volumes:
      - ./db/data:/var/lib/mysql
