version: '3.9'

services:
  front:
    build: ./Front
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - backend
      - db
    volumes:
      - ./Front/src:/usr/share/nginx/html
    networks:
        portafolio:

  backend:
    build: ./Backend
    container_name: flask
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./Backend/app:/app
    depends_on:
      - db
    networks:
        portafolio:

  db:
      image: mongo:6.0.3
      container_name: db-mongo
      restart: always
      ports:
        - 27018:27017
      env_file:
        - common.env
      volumes:
        - ./db/datadir:/data/db
      networks:
        portafolio:

networks:
  portafolio:
    name: network-portafolio
    driver: bridge
    ipam:
      config:
        - subnet: "172.23.0.0/16"
          gateway: "172.23.0.1"